---
## rec.yaml
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec-demo
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: standard        # GCP specific
  uiServiceType: LoadBalancer         # No tunneling to the UI needed
  redisEnterpriseNodeResources:
    limits:
      cpu: 4                          # Assumes at least 6 cores
      memory: 4Gi
    requests:
      cpu: 4
      memory: 4Gi
