---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: andre-rec-demo
spec:
  nodes: 3
  persistenceSpec:
    enabled: true
    storageClassName: "standard" # GCP specific
  uiServiceType: LoadBalancer
  redisEnterpriseNodeResources:
    limits:
      cpu: 4000m  
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
