---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: andre-rec-demo-portworx
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "sc-portworx"
  redisEnterpriseNodeResources:
    limits:
      cpu: 4000m  
      memory: 4Gi
    requests:
      cpu: 4000m
      memory: 4Gi
